# Generated by Django 5.1.2 on 2024-10-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Если стоит галочка, то объект считается удаленным', verbose_name='Удален')),
                ('name', models.CharField(help_text='Ввведите имя города', max_length=63, verbose_name='Имя города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
