# Generated by Django 5.1.2 on 2024-10-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterField(
            model_name='city',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Если стоит галочка, то объект считается удаленным', verbose_name='Удален'),
        ),
    ]
