# Generated by Django 5.1.2 on 2025-04-20 12:40

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nanny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона работника', max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('cost_per_hour', models.PositiveIntegerField(help_text='Введите стоимость в час', null=True, validators=[django.core.validators.MinValueValidator(450)], verbose_name='Стоимость в час')),
                ('photo', models.ImageField(help_text='Загрузите фото', null=True, upload_to='', verbose_name='Фото работника')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Дата создания няни', verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, help_text='Дата обновления данных няни', verbose_name='Дата обновления')),
                ('work_days', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')], default=0, help_text='Выберите рабочие дни недели', max_length=13, verbose_name='Рабочие дни недели')),
                ('age', models.PositiveSmallIntegerField(help_text='Введите возраст', verbose_name='Возраст')),
                ('experience', models.PositiveSmallIntegerField(help_text='Введите кол-во лет', verbose_name='Опыт')),
                ('describe', models.TextField(help_text='Введите описание', verbose_name='Описание')),
                ('city', models.ForeignKey(help_text='Города, в которых работает работник', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_infrastructure.city', verbose_name='Города')),
                ('user', models.OneToOneField(help_text='Выберите аккаунт работника', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт работника')),
            ],
            options={
                'verbose_name': 'Няня',
                'verbose_name_plural': 'Няни',
            },
        ),
    ]
