# Generated by Django 5.1.2 on 2024-10-22 00:18

import apps.app_contrib.fields.weekdays
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nanny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона работника', max_length=128, region=None, verbose_name='Номер телефона')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Дата создания няни', verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, help_text='Дата обновления данных няни', verbose_name='Дата обновления')),
                ('work_days', apps.app_contrib.fields.weekdays.WeekdayField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], help_text='Выберите рабочие дни недели', max_length=7, verbose_name='Рабочие дни недели')),
                ('describe', models.TextField(help_text='Введите описание', verbose_name='Описание')),
                ('skills', models.TextField(help_text='Что вы умеете?', verbose_name='Навыки')),
                ('city', models.ForeignKey(help_text='Города, в которых работает работник', on_delete=django.db.models.deletion.DO_NOTHING, to='app_infrastructure.city', verbose_name='Города')),
                ('user', models.ForeignKey(help_text='Выберите аккаунт работника', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт работника')),
            ],
            options={
                'verbose_name': 'Няня',
                'verbose_name_plural': 'Няни',
            },
        ),
    ]
