# Generated by Django 5.1.2 on 2024-11-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanny',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='nanny',
            name='last_name',
            field=models.CharField(default='', max_length=150, verbose_name='last name'),
        ),
    ]
