# Generated by Django 5.1.2 on 2025-04-22 08:14

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanny',
            name='additional_services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cleaning', 'Няни с обязанностями по уборке'), ('cooking', 'Няни с обязанностями по приготовлению пищи'), ('tutoring', 'Няни с образовательной функцией (репетиторы)'), ('special_needs', 'Няни с навыками ухода за детьми с особыми потребностями')], default='---', help_text='Выберите дополнительные услуги', max_length=50, verbose_name='Дополнительные услуги'),
        ),
        migrations.AddField(
            model_name='nanny',
            name='age_groups',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('newborns', 'Няни для новорожденных'), ('under_3', 'Няни для детей до 3 лет'), ('ages_3_7', 'Няни для детей 3-7 лет'), ('schoolkids', 'Няни для школьников')], default='---', help_text='Выберите возрастные группы детей', max_length=50, verbose_name='Возрастные группы детей'),
        ),
        migrations.AddField(
            model_name='nanny',
            name='foreign_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('english', 'Английский'), ('french', 'Французский')], default='---', help_text='Выберите иностранные языки', max_length=100, verbose_name='Иностранные няни'),
        ),
        migrations.AddField(
            model_name='nanny',
            name='living_arrangements',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('live_in', 'Няни, проживающие с семьей'), ('live_out', 'Няни, приходящие на работу')], default='---', help_text='Выберите тип проживания', max_length=30, verbose_name='Проживание'),
        ),
        migrations.AddField(
            model_name='nanny',
            name='qualification_levels',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('experienced', 'Опытные няни (с опытом работы)'), ('medical', 'Няни с медицинским образованием'), ('pedagogical', 'Няни с педагогическим образованием'), ('beginner', 'Няни без опыта (студенты, начинающие)')], default='---', help_text='Выберите уровень квалификации', max_length=50, verbose_name='Уровень квалификации'),
        ),
        migrations.AddField(
            model_name='nanny',
            name='work_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('full_day', 'Няни на полный день'), ('part_day', 'Няни на неполный день'), ('weekends', 'Няни на выходные'), ('hourly', 'Няни по часам'), ('temporary', 'Няни для временной работы')], default='---', help_text='Выберите тип работы', max_length=50, verbose_name='Тип работы'),
        ),
    ]
