# Generated by Django 5.1.2 on 2024-10-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanny',
            name='cost_per_hour',
            field=models.PositiveIntegerField(default=0, help_text='Введите стоимость в час', verbose_name='Стоимость в час'),
        ),
        migrations.AddField(
            model_name='nanny',
            name='experience',
            field=models.PositiveSmallIntegerField(default=0, help_text='Введите кол-во лет', verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='nanny',
            name='photo',
            field=models.ImageField(help_text='Загрузите фото', null=True, upload_to='', verbose_name='Фото работника'),
        ),
    ]
