# Generated by Django 5.1.2 on 2024-11-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0002_nanny_first_name_nanny_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanny',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
