# Generated by Django 5.1.2 on 2024-10-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0002_nanny_cost_per_hour_nanny_experience_nanny_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanny',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, help_text='Введите возраст', verbose_name='Возраст'),
        ),
    ]
