# Generated by Django 5.1.2 on 2024-10-27 14:40

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0003_nanny_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanny',
            name='work_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')], default=0, help_text='Выберите рабочие дни недели', max_length=7, verbose_name='Рабочие дни недели'),
        ),
    ]
