# Generated by Django 5.1.2 on 2024-11-01 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0003_alter_nanny_first_name_alter_nanny_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanny',
            name='user',
            field=models.OneToOneField(help_text='Выберите аккаунт работника', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт работника'),
        ),
    ]
