# Generated by Django 5.1.2 on 2024-10-27 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0004_nanny_work_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nanny',
            name='skills',
        ),
        migrations.AlterField(
            model_name='nanny',
            name='cost_per_hour',
            field=models.PositiveIntegerField(default=450, help_text='Введите стоимость в час', validators=[django.core.validators.MinValueValidator(450)], verbose_name='Стоимость в час'),
        ),
    ]
