# Generated by Django 5.1.2 on 2024-11-01 23:02

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0004_alter_nanny_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanny',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, help_text='Введите возраст', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='describe',
            field=models.TextField(default='', help_text='Введите описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='experience',
            field=models.PositiveSmallIntegerField(default=0, help_text='Введите кол-во лет', verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='work_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')], default=0, help_text='Выберите рабочие дни недели', max_length=7, verbose_name='Рабочие дни недели'),
        ),
    ]
