# Generated by Django 5.1.2 on 2024-11-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_worker', '0005_alter_nanny_age_alter_nanny_describe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanny',
            name='age',
            field=models.PositiveSmallIntegerField(help_text='Введите возраст', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='describe',
            field=models.TextField(help_text='Введите описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='experience',
            field=models.PositiveSmallIntegerField(help_text='Введите кол-во лет', verbose_name='Опыт'),
        ),
    ]
