# Generated by Django 5.1.2 on 2024-10-28 01:23

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_infrastructure', '0001_initial'),
        ('app_worker', '0005_remove_nanny_skills_alter_nanny_cost_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanny',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, help_text='Введите возраст', null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='city',
            field=models.ForeignKey(help_text='Города, в которых работает работник', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_infrastructure.city', verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='cost_per_hour',
            field=models.PositiveIntegerField(default=450, help_text='Введите стоимость в час', null=True, validators=[django.core.validators.MinValueValidator(450)], verbose_name='Стоимость в час'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='describe',
            field=models.TextField(help_text='Введите описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='experience',
            field=models.PositiveSmallIntegerField(default=0, help_text='Введите кол-во лет', null=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона работника', max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='work_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')], default=0, help_text='Выберите рабочие дни недели', max_length=7, null=True, verbose_name='Рабочие дни недели'),
        ),
    ]
