[tool.poetry]
name = "www"
version = "0.1.0"
description = ""
authors = ["Ринат Кучаев <RZKuchaev@stud.kpfu.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.1"
django-phonenumber-field = {extras = ["phonenumberslite"], version = "^8.0.0"}
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
