# Generated by Django 5.1.2 on 2024-11-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(default='', help_text='Основной текст блока. Максимум 2047 символов', max_length=2047, verbose_name='Информация о клиенте, который написал отзыв'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(help_text='Основной текст блока. Максимум 2047 символов', max_length=2047, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(help_text='Отображается сверху блока. Максимум 1023 символа', max_length=1023, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='review',
            name='from_client',
            field=models.CharField(help_text='Отображается сверху блока. Максимум 255 символа', max_length=255, verbose_name='Информация о клиенте, который написал отзыв'),
        ),
    ]
