# Generated by Django 5.1.2 on 2024-11-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_home', '0002_review_text_alter_faq_answer_alter_faq_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(help_text='Основной текст блока. Максимум 2047 символов', max_length=2047, verbose_name='Информация о клиенте, который написал отзыв'),
        ),
    ]
