# Generated by Django 5.1.2 on 2025-01-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_home', '0004_alter_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(help_text='Номер, по которому определяется порядок отзыва в блоке с отзывами', verbose_name='Порядковый номер')),
                ('from_client', models.CharField(help_text='Отображается сверху блока. Максимум 255 символа', max_length=255, verbose_name='Информация о клиенте, который написал отзыв')),
                ('preview', models.ImageField(upload_to='reviews/img', verbose_name='Загрузить превью к аудиоотзыву')),
                ('file', models.FileField(help_text='Загрузите аудио с отзывом клиента', upload_to='reviews/audio', verbose_name='Аудио')),
            ],
            options={
                'verbose_name': 'Аудиоотзыв',
                'verbose_name_plural': 'Аудиоотзывы',
            },
        ),
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(help_text='Номер, по которому определяется порядок отзыва в блоке с отзывами', verbose_name='Порядковый номер')),
                ('from_client', models.CharField(help_text='Отображается сверху блока. Максимум 255 символа', max_length=255, verbose_name='Информация о клиенте, который написал отзыв')),
                ('preview', models.ImageField(null=True, upload_to='reviews/img', verbose_name='Вы можете добавить превью к видеоотзыву')),
                ('file', models.FileField(help_text='Загрузите видео с отзывом клиента', upload_to='reviews/video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видеоотзыв',
                'verbose_name_plural': 'Видеоотзывы',
            },
        ),
    ]
