# Generated by Django 5.1.2 on 2025-03-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_home', '0005_audioreview_videoreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoreview',
            name='text',
            field=models.CharField(help_text='Основной текст блока. Максимум 2047 символов', max_length=2047, null=True, verbose_name='Отзыв'),
        ),
    ]
