# Generated by Django 5.1.1 on 2024-10-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Ввведите имя города', max_length=63, verbose_name='Имя города')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
