# Generated by Django 5.1.2 on 2024-10-22 00:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Если стоит галочка, то объект считается удаленным', verbose_name='Удален')),
                ('name', models.CharField(help_text='Введите название подписки', max_length=255, verbose_name='Название подписки')),
                ('short_description', models.CharField(help_text='Введите описание подписки (максимальное количество символов 255)', max_length=255, verbose_name='Описание подписки')),
                ('client_type', models.CharField(choices=[('N', 'Няни'), ('P', 'Родители')], help_text='Выберите тип клиент, для которого работает эта подписка', max_length=1, verbose_name='Тип клиента')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость подписки', max_digits=15, verbose_name='Стоимость подписки')),
                ('day_range', models.PositiveSmallIntegerField(default=0, help_text='Продолжительность работы подписки в днях', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Дни')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Дата создания подписки', verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, help_text='Дата обновления данных о подписке', verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('subscribe', models.ForeignKey(help_text='Подписка, которую оформил пользователь', on_delete=django.db.models.deletion.CASCADE, to='app_subscribe.subscribe', verbose_name='Подписка')),
                ('user', models.ForeignKey(help_text='Пользователь, который оформил подписку', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
