# Generated by Django 5.1.2 on 2024-10-22 17:28

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersubscribe',
            managers=[
                ('leftover', django.db.models.manager.Manager()),
            ],
        ),
    ]
