# Generated by Django 5.1.2 on 2024-10-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscribe', '0002_alter_usersubscribe_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscribe',
            options={'verbose_name': 'Подписка пользователя', 'verbose_name_plural': 'Подписки пользователей'},
        ),
    ]
