# Generated by Django 5.1.2 on 2024-10-28 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscribe', '0003_alter_usersubscribe_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersubscribe',
            managers=[
            ],
        ),
    ]
