# Generated by Django 5.1.2 on 2024-10-21 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscribe', '0003_alter_subscribe_options_subscribe_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='month_range',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='year_range',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='day_range',
            field=models.PositiveSmallIntegerField(default=0, help_text='Продолжительность работы подписки в днях', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Дни'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Если стоит галочка, то объект считается удаленным', verbose_name='Удален'),
        ),
    ]
