# Generated by Django 5.1.1 on 2024-10-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='date_range',
            new_name='day_range',
        ),
    ]
