# Generated by Django 5.1.1 on 2024-10-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscribe', '0002_rename_date_range_subscribe_day_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='subscribe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='client_type',
            field=models.CharField(choices=[('N', 'Няни'), ('P', 'Родители')], help_text='Выберите тип клиент, для которого работает эта подписка', max_length=1, verbose_name='Тип клиента'),
        ),
    ]
