# Generated by Django 5.1.2 on 2025-03-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_type',
            field=models.CharField(choices=[('N', 'Няни'), ('P', 'Родители')], default=1, help_text='Выберите тип пользователя', max_length=1, verbose_name='Тип пользователя'),
        ),
    ]
