# Generated by Django 5.1.2 on 2025-03-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_infrastructure', '0001_initial'),
        ('app_user', '0004_alter_user_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_infrastructure.city', verbose_name='Город пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_type',
            field=models.CharField(choices=[('N', 'Няни'), ('P', 'Родители')], help_text='Выберите тип пользователя', max_length=1, null=True, verbose_name='Тип пользователя'),
        ),
    ]
